### ISSUE TITLE
Step 3.9 - Problem with typings? (Cannot find name 'Meteor')

### ISSUE THREAD

**Issue by stefanholzapfel** [Urigo/meteor-angular2.0-socially#65]
Hi guys!

From step 3.9 in the "socially" tutorial I get the error  "server/main.ts (3, 1): Cannot find name 'Meteor'."

I already downloaded the typings file from https://gist.github.com/tomitrescak/8366ce98f1857e202ea8, put it into the typings folder and referenced it in the main.d.ts (`/// <reference path="meteor.d.ts" />`).

Furthermore I added the main.d.ts to the tsconfig.json (as proposed in another issue thread), now it looks like:

`{`
  `"compilerOptions": {`
    `"experimentalDecorators": true,`
    `"module": "commonjs",`
    `"target": "es5",`
    `"isolatedModules": false,`
    `"moduleResolution": "node",`
    `"emitDecoratorMetadata": true,`
    `"removeComments": false,`
    `"noImplicitAny": false,`
    `"sourceMap": true`
  `},`
  `"files": [`
    `"typings/main.d.ts"`
  `]`
`}`

server/main.ts contains only:

`import {loadParties} from './load-parties.ts';`
`Meteor.startup(loadParties);`

Any help is highly appreciated!

**Comment by davidbonachera** [comment]
Exact same error.

**Comment by kuncevic** [comment]
Got in to similar issue with typings. Here is full error log attached [meteor_errors.txt](https://github.com/Urigo/meteor-angular2.0-socially/files/234444/meteor_errors.txt)
Usually tyescript projects contains file `typings.json` with all typescript defs which is missed in the current one.

When open project in vscode getting errors:
`[ts] Cannot find name 'Meteor'.`
`[ts] Cannot find module 'meteor/tmeasday:publish-counts'`
`[ts] Cannot find module 'meteor/socially-browser'.`
`[ts] Cannot find module 'meteor/socially-mobile'.`

Tried same steps as @stefanholzapfel done - no luck.

**Comment by hongbo-miao** [comment]
@kuncevich the reason you got

> [ts] Cannot find module 'meteor/tmeasday:publish-counts'
> [ts] Cannot find module 'meteor/socially-browser'.
> [ts] Cannot find module 'meteor/socially-mobile'.

is because meteor.d.ts does not include those. If you want to get rid of that warning. So for example, instead of
`import SimpleSchema from 'meteor/SimpleSchema';`
I will add
`declare const SimpleSchema: any;`
in any typing file.

But for

> [ts] Cannot find name 'Meteor'.

Hope someone else can help you.

**Comment by Ryuzavi** [comment]
edit - nvm, fixed with the proper typings install - `typings install meteor --ambient`

**Comment by hongbo-miao** [comment]
@Ryuzavi and all, it should be `typings install registry:env/meteor --ambient` now.
Refer to https://github.com/Urigo/angular2-meteor/issues/246

**Comment by kuncevic** [comment]
Obviously RC.x will break things even more

**Comment by Ryuzavi** [comment]
@Hongbo-Miao I was trying with that one originally but the issue didn't go away until I did the older version :/

**Comment by stefanholzapfel** [comment]
I tried to replace the typings from tomitrescak with the ones from env/meteor, but I still get the same error:
server/main.ts (3, 1): Cannot find name 'Meteor'.

**Comment by johnking** [comment]
@Ryuzavi , I have to do the same thing as you did to get rid of the warning/errors.

i.e, typings install meteor --ambient

**Comment by Urigo** [comment]
should work now with the new typings instructions.
if not, please open a new issue
